@startuml EPD

state "Sein op groen" as SeinOpGroen
state "Sein op oranje" as SeinOpOranje
state "Sein op rood" as SeinOpRood
state "Slagbomen dalen" as SlagbomenDalen
state "Slagbomen gesloten" as SlagbomenGesloten
state "Trein passeert" as TreinPasseert
state "Slagbomen stijgen" as SlagbomenStijgen

[*] --> SeinOpGroen

SeinOpGroen --> SeinOpOranje : Trein nadert
SeinOpOranje --> SeinOpRood : Na 1,5 seconden
SeinOpRood --> SlagbomenDalen

SlagbomenDalen --> SlagbomenGesloten : Slagbomen volledig gesloten
SlagbomenGesloten --> TreinPasseert : Trein rijdt over de overgang
TreinPasseert --> SlagbomenStijgen : Trein voorbij
SlagbomenStijgen --> SeinOpGroen : Slagbomen volledig geopend
@enduml