#include "request.h"
#include "cserver.h"

const struct target_config ENDPOINTS_CONFIG[11] = {
    {CONFIG_MODE,
     "/config/mode",
     {METHOD_PUT},
     handlePutConfigMode},
    {CONFIG_CBUFFSIZE,
     "/config/cbuffsize",
     {METHOD_PUT},
     handlePutConfigCbuffsize},
    {SENSORS_1,
     "/sensors/1",
     {METHOD_POST, METHOD_DELETE},
     handleSensors1},
    {SENSORS_2,
     "/sensors/2",
     {METHOD_POST, METHOD_DELETE},
     handleSensors2},
    {SENSORS_1_AVG,
     "/sensors/1/avg",
     {METHOD_GET},
     handleGetSensors1Avg},
    {SENSORS_2_AVG,
     "/sensors/2/avg",
     {METHOD_GET},
     handleGetSensors2Avg},
    {SENSORS_1_STDEV,
     "/sensors/1/stdev",
     {METHOD_GET},
     handleGetSensors1Stdev},
    {SENSORS_2_STDEV,
     "/sensors/2/stdev",
     {METHOD_GET},
     handleGetSensors2Stdev},
    {SENSORS_1_ACTUAL,
     "/sensors/1/actual",
     {METHOD_GET},
     handleGetSensors1Actual},
    {SENSORS_2_ACTUAL,
     "/sensors/2/actual",
     {METHOD_GET},
     handleGetSensors2Actual},
    {ROOT, "/", {METHOD_GET}, handleOnlineCheck}};
